[[redirects]]
  from = "/api/*"
  to = "https://m3-hub-mvp1-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/colyseus/*"
  to = "https://m3-hub-mvp1-production.up.railway.app/colyseus/:splat"
  status = 200
  force = true